language: minimal

services:
  - docker



# Scripts to be run such as tests

script:
  - docker --version # print the version for logging
  - cd udacity-c3-frontend
  - docker build -t udacity-project-4-frontend .
  - docker tag udacity-project-4-frontend jordan27docker/udacity-project-4-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jordan27docker/udacity-project-4-frontend
  - docker run jordan27docker/udacity-project-4-frontend
  - docker ps - a