export POSTGRESS_USERNAME = "udagrammicro"
export POSTGRESS_PASSWORD = "wahjiwah123"
export POSTGRESS_DB = "postgres"
export POSTGRESS_HOST = "udagrammicro.cbctgfxv2p5k.us-east-1.rds.amazonaws.com"
export AWS_REGION = "us-east-1"
export AWS_PROFILE = "default"
export AWS_BUCKET = "udagram-images-dex"
export JWT_SECRET = "ajjawkjfbwkejjfjf"